#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-core
Version  : 1.2.1
Release  : 3
URL      : https://rubygems.org/downloads/dm-core-1.2.1.gem
Source0  : https://rubygems.org/downloads/dm-core-1.2.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec

%description
= Why DataMapper?
== Open Development
DataMapper sports a very accessible code-base and a welcoming community.
Outside contributions and feedback are welcome and encouraged, especially
constructive criticism. Make your voice heard! Submit a
ticket[https://github.com/datamapper/dm-core/issues] or
patch[http://datamapper.lighthouseapp.com], speak up
on our mailing-list[http://groups.google.com/group/datamapper/], chat with us
on irc[irc://irc.freenode.net/#datamapper], write a spec, get it reviewed, ask
for commit rights. It's as easy as that to become a contributor.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-core-1.2.1
gem spec %{SOURCE0} -l --ruby > rubygem-dm-core.gemspec

%build
gem build rubygem-dm-core.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-core-1.2.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/dm-core-1.2.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/.document
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/dm-core.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/adapters.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/adapters/abstract_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/adapters/in_memory_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/associations/many_to_many.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/associations/many_to_one.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/associations/one_to_many.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/associations/one_to_one.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/associations/relationship.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/backwards.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/core_ext/kernel.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/core_ext/pathname.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/core_ext/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/identity_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/model.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/model/hook.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/model/is.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/model/property.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/model/relationship.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/model/scope.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/binary.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/boolean.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/class.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/date_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/decimal.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/discriminator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/float.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/integer.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/lookup.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/numeric.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/serial.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/typecast/numeric.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property/typecast/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/property_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/query.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/query/conditions/comparison.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/query/conditions/operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/query/direction.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/query/operator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/query/path.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/query/sort.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/relationship_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/repository.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/resource.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/clean.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/deleted.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/dirty.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/immutable.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/persisted.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/resource/persistence_state/transient.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/lib/adapter_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/lib/collection_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/lib/counter_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/lib/pending_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/lib/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/shared/adapter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/shared/public/property_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/shared/resource_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/shared/sel_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/shared/semipublic/property_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/spec/shared/semipublic/query/conditions/abstract_comparison_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/assertions.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/chainable.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/deprecate.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/equalizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ext/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ext/blank.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ext/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ext/module.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ext/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ext/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ext/try_dup.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/hook.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/inflections.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/inflector/inflections.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/inflector/methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/local_object_space.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/mash.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/naming_conventions.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/subject.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/script/performance.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/script/profile.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/lib/rspec_immediate_feedback_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/associations/many_to_many/read_multiple_join_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/associations/many_to_many_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/associations/many_to_one_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/associations/many_to_one_with_boolean_cpk_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/associations/many_to_one_with_custom_fk_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/associations/one_to_many_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/associations/one_to_one_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/associations/one_to_one_with_boolean_cpk_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/collection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/finalize_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/model/hook_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/model/property_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/model/relationship_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/model_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/binary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/boolean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/date_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/decimal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/discriminator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/serial_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/text_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property/time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/property_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/resource/state_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/resource_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/sel_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/setup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/shared/association_collection_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/shared/collection_finder_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/shared/collection_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/public/shared/finder_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/rcov.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/adapters/abstract_adapter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/adapters/in_memory_adapter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/associations/many_to_many_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/associations/many_to_one_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/associations/one_to_many_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/associations/one_to_one_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/associations/relationship_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/associations_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/collection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/model_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/binary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/boolean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/class_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/date_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/decimal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/discriminator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/lookup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/serial_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/text_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property/time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/property_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/query/conditions/comparison_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/query/conditions/operation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/query/path_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/query_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/resource/state/clean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/resource/state/deleted_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/resource/state/dirty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/resource/state/immutable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/resource/state/transient_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/resource/state_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/resource_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/shared/condition_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/shared/resource_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/shared/resource_state_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/semipublic/shared/subject_shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/support/core_ext/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/support/core_ext/inheritable_attributes.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/support/properties/huge_integer.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/blank_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/append_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/clear_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/delete_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/each_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/empty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/entries_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/eql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/equal_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/hash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/include_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/index_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/initialize_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/merge_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/append_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/clear_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/delete_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/each_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/empty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/entries_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/include_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/index_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/initialize_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/merge_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/size_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/shared/to_ary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/size_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/ordered_set/to_ary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/append_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/clear_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/delete_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/each_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/empty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/entries_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/get_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/include_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/named_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/append_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/clear_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/delete_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/each_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/empty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/entries_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/get_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/include_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/named_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/size_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/to_ary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/shared/values_at_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/size_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/to_ary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/data_mapper/subject_set/values_at_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/hash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/hook_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/lazy_array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/mash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/module_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/spec/unit/try_dup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/tasks/ci.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/tasks/spec.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-core-1.2.1/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/specifications/dm-core-1.2.1.gemspec
